# Importing modules and settings

In [1]:
import numpy as np
import pandas as pd
import scanpy as sc

In [2]:
pd.options.display.float_format = '{:,.3f}'.format

In [3]:
pd.set_option('use_inf_as_na',True)

General settings of Scanpy

In [4]:
sc.settings.verbosity = 3 
sc.logging.print_header()
sc.settings.set_figure_params(dpi=80, facecolor='white')

scanpy==1.9.1 anndata==0.9.1 umap==0.5.3 numpy==1.21.5 scipy==1.7.3 pandas==1.4.2 scikit-learn==1.0.2 statsmodels==0.13.2 python-igraph==0.9.11 pynndescent==0.5.7

# Declaring the input file

This notebook needs to read the adata processed object and the matrix unprocessed.

The adata processed object

In [5]:
adata = sc.read_h5ad('./Serotonergic_data_annotated.h5ad')

The matrix unprocessed will be adata_u

In [6]:
adata_u = sc.read_10x_mtx(
    "../0 Reads Processing/Sero_matrix",
    var_names='gene_symbols',
    cache=True)

... reading from cache file cache\..-0 Reads Processing-Sero_matrix-matrix.h5ad

In [7]:
adata.var

,gene_ids,feature_types,longest_isoform,gene_type,gene_JakkeGuo,gene_Jakke_ver1,gene_ddv6,jakkeguo_collapsed,jakke_ver1_collapsed,ddv6_collapsed,...,n_cells_by_counts,mean_counts,pct_dropout_by_counts,total_counts,highly_variable,means,dispersions,dispersions_norm,mean,std
h1SMcG0000008,h1SMcG0000008,Gene Expression,h1SMcT0000008.1,hconf,SMEST029651001.1,SMEST029651001.1,dd_Smed_v6_35379_0_1,"SMEST029651001.1,SMEST029651002.1,SmMSTRG.9911...","SMEST029651001.1,SMEST029651002.1",dd_Smed_v6_35379_0_1,...,10,0.000,99.979,11.000,True,0.000,0.478,1.456,0.000,0.013
h1SMcG0000009,h1SMcG0000009,Gene Expression,h1SMcT0000009.2,hconf,SMEST029652002.1,SMEST029652002.1,dd_Smed_v6_5323_0_1,"SMEST029652002.1,SmMSTRG.9914.2,SmMSTRG.9914.3...",SMEST029652002.1,dd_Smed_v6_5323_0_1,...,196,0.004,99.586,197.000,True,0.003,0.036,0.147,0.002,0.039
h1SMcG0000011,h1SMcG0000011,Gene Expression,h1SMcT0000011.1,hconf,SMEST029655001.1,SMEST029655001.1,dd_Smed_v6_6416_0_1,"SMEST029655001.1,SMEST029655002.1,SmMSTRG.9916...","SMEST029655001.1,SMEST029655002.1",dd_Smed_v6_6416_0_1,...,2366,0.053,95.005,"2,525.000",True,0.045,0.141,0.456,0.031,0.146
h1SMcG0000012,h1SMcG0000012,Gene Expression,h1SMcT0000012.1,hconf,SmMSTRG.9913.2,SMEST029666001.1,dd_Smed_v6_20296_0_1,"SMEST029666001.1,SmMSTRG.9913.2",SMEST029666001.1,dd_Smed_v6_20296_0_1,...,25,0.001,99.947,26.000,True,0.000,0.186,0.590,0.000,0.015
h1SMcG0000013,h1SMcG0000013,Gene Expression,h1SMcT0000013.5,hconf,SmMSTRG.9917.1,MSTRG.9917.1,dd_Smed_v6_4708_0_1,"SMEST029667004.1,SmMSTRG.9917.1,SmMSTRG.9917.2...","MSTRG.9917.1,SMEST029667004.1",dd_Smed_v6_4708_0_1,...,681,0.015,98.562,705.000,True,0.013,0.100,0.336,0.009,0.077
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
h1SMnG0034970,h1SMnG0034970,Gene Expression,h1SMnT0034970.1,other,-,-,-,-,-,-,...,2,0.000,99.996,2.000,True,0.000,0.120,0.396,0.000,0.004
h1SMnG0035064,h1SMnG0035064,Gene Expression,h1SMnT0035064.1,other,-,-,-,-,-,-,...,1,0.000,99.998,1.000,True,0.000,0.226,0.708,0.000,0.004
h1SMnG0035227,h1SMnG0035227,Gene Expression,h1SMnT0035227.1,other,-,-,-,-,-,-,...,2,0.000,99.996,2.000,True,0.000,0.321,0.992,0.000,0.005
h1SMnG0035258,h1SMnG0035258,Gene Expression,h1SMnT0035258.1,hconf,-,-,-,-,-,-,...,3,0.000,99.994,3.000,True,0.000,0.376,1.152,0.000,0.007
h1SMnG0035302,h1SMnG0035302,Gene Expression,h1SMnT0035302.1,other,-,-,-,-,-,-,...,2,0.000,99.996,2.000,True,0.000,0.086,0.294,0.000,0.005

In [8]:
adata.obs

,sample,biological_rep,technical_rep,library,sample_bio,unique,sample_rep,unique_rep,n_counts,n_genes,...,pct_counts_mt,leiden_1,leiden_2,leiden_3,leiden_4,ingest_names,transferred,leiden_3_names_collapsed,leiden_3_names,broad_names
L43_1_AACCATTGGAGACTAGTAACGCTCGA,gfp(RNAi),B2,T2,Lib1,gfp(RNAi)_B2,gfp(RNAi)_Lib1,gfp(RNAi)_B2_T2,gfp(RNAi)_B2_T2_Lib1,148.000,130,...,0.000,8,9,7,25,pgrn+ parenchymal cells 1,pgrn+ parenchymal cells 1,pgrn+ parenchymal cells 1,pgrn+ parenchymal cells 1,parenchymal
L43_1_CATTCGACGGAGATCGCACGCTGATC,gfp(RNAi),B2,T2,Lib1,gfp(RNAi)_B2,gfp(RNAi)_Lib1,gfp(RNAi)_B2_T2,gfp(RNAi)_B2_T2_Lib1,176.000,159,...,0.000,1,1,1,0,chat+ neurons 1,chat+ neurons 1,chat+ neurons 1,chat+ neurons 1,neurons
L43_1_ACGGAGGCGGTGGAACAATAGGATGA,gfp(RNAi),B2,T1,Lib1,gfp(RNAi)_B2,gfp(RNAi)_Lib1,gfp(RNAi)_B2_T1,gfp(RNAi)_B2_T1_Lib1,502.000,359,...,0.000,0,0,0,7,neoblasts 1,neoblasts 1,neoblasts,neoblasts 1,neoblasts
L43_1_GACCTTGATAACGCTCGACAAGACTA,gfp(RNAi),B2,T2,Lib1,gfp(RNAi)_B2,gfp(RNAi)_Lib1,gfp(RNAi)_B2_T2,gfp(RNAi)_B2_T2_Lib1,185.000,149,...,0.000,4,3,9,5,early epidermal progenitors,early epidermal progenitors,early epidermal progenitors 1,early epidermal progenitors 1,epidermal
L43_1_TTACCTCGACTGGAACAAAGATCGCA,lhx1/5-1(RNAi),B1,T2,Lib1,lhx1/5-1(RNAi)_B1,lhx1/5-1(RNAi)_Lib1,lhx1/5-1(RNAi)_B1_T2,lhx1/5-1(RNAi)_B1_T2_Lib1,180.000,166,...,0.000,2,6,3,9,intestinal and DV muscle,intestinal and DV muscle,intestinal and DV muscle,intestinal and DV muscle,muscle
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
L43_5_TAACTGGTTAAAGGTACAGAGTTAGC,gfp(RNAi),B2,T2,Lib5,gfp(RNAi)_B2,gfp(RNAi)_Lib5,gfp(RNAi)_B2_T2,gfp(RNAi)_B2_T2_Lib5,411.000,212,...,0.000,7,37,26,49,epidermis,epidermis,epidermis 2,epidermis 2,epidermal
L43_5_GGTACCGGCAGAATCTGATGAAGAGA,gfp(RNAi),B2,T2,Lib5,gfp(RNAi)_B2,gfp(RNAi)_Lib5,gfp(RNAi)_B2_T2,gfp(RNAi)_B2_T2_Lib5,262.000,186,...,0.000,0,0,5,4,neoblasts 1,neoblasts 1,neoblasts,neoblasts 3,neoblasts
L43_5_GCCGCAACGACCAGTTCAAGCAGGAA,gfp(RNAi),B1,T2,Lib5,gfp(RNAi)_B1,gfp(RNAi)_Lib5,gfp(RNAi)_B1_T2,gfp(RNAi)_B1_T2_Lib5,110.000,103,...,0.000,5,8,6,3,pgrn+ parenchymal cells 2,pgrn+ parenchymal cells 2,pgrn+ parenchymal cells 2,pgrn+ parenchymal cells 2,parenchymal
L43_5_CCAGTTCCAATGGAACAAATTGGCTC,gfp(RNAi),B2,T1,Lib5,gfp(RNAi)_B2,gfp(RNAi)_Lib5,gfp(RNAi)_B2_T1,gfp(RNAi)_B2_T1_Lib5,238.000,201,...,0.000,1,1,1,0,chat+ neurons 1,chat+ neurons 1,chat+ neurons 1,chat+ neurons 1,neurons
L43_5_TTCGCCTCCACAAGGAGCAAACATCG,lhx1/5-1(RNAi),B1,T2,Lib5,lhx1/5-1(RNAi)_B1,lhx1/5-1(RNAi)_Lib5,lhx1/5-1(RNAi)_B1_T2,lhx1/5-1(RNAi)_B1_T2_Lib5,230.000,138,...,0.000,3,33,38,43,committed neoblasts,neoblasts 1,neoblasts,neoblasts 4,neoblasts

In [9]:
adata

AnnData object with n_obs × n_vars = 47292 × 24000
    obs: 'sample', 'biological_rep', 'technical_rep', 'library', 'sample_bio', 'unique', 'sample_rep', 'unique_rep', 'n_counts', 'n_genes', 'n_genes_by_counts', 'total_counts', 'total_counts_mt', 'pct_counts_mt', 'leiden_1', 'leiden_2', 'leiden_3', 'leiden_4', 'ingest_names', 'transferred', 'leiden_3_names_collapsed', 'leiden_3_names', 'broad_names'
    var: 'gene_ids', 'feature_types', 'longest_isoform', 'gene_type', 'gene_JakkeGuo', 'gene_Jakke_ver1', 'gene_ddv6', 'jakkeguo_collapsed', 'jakke_ver1_collapsed', 'ddv6_collapsed', 'Preferred_name', 'Description', 'PFAMs', 'mt', 'n_cells_by_counts', 'mean_counts', 'pct_dropout_by_counts', 'total_counts', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'biological_replicates', 'dendrogram_leiden_1', 'dendrogram_leiden_2', 'dendrogram_leiden_3', 'dendrogram_leiden_4', 'hvg', 'ingest_names_colors', 'leiden', 'leiden_1_colors', 'leiden_2_colors', 'leiden_3_colors', 'leiden_3_names_collapsed_colors', 'leiden_3_names_colors', 'leiden_4_colors', 'library_colors', 'log1p', 'neighbors', 'pca', 'rank_genes_groups_logreg_leiden_1', 'rank_genes_groups_logreg_leiden_2', 'rank_genes_groups_logreg_leiden_3', 'rank_genes_groups_logreg_leiden_4', 'rank_genes_groups_wilcox_leiden_1', 'rank_genes_groups_wilcox_leiden_2', 'rank_genes_groups_wilcox_leiden_3', 'rank_genes_groups_wilcox_leiden_4', 'sample_colors', 'samples', 'technical_replicates', 'transferred_colors', 'umap'
    obsm: 'X_pca', 'X_umap'
    varm: 'PCs'
    obsp: 'connectivities', 'distances'

In [10]:
adata_u.var

                    gene_ids    feature_types
h1SMcG0000001  h1SMcG0000001  Gene Expression
h1SMcG0000002  h1SMcG0000002  Gene Expression
h1SMcG0000006  h1SMcG0000006  Gene Expression
h1SMcG0000008  h1SMcG0000008  Gene Expression
h1SMcG0000009  h1SMcG0000009  Gene Expression
...                      ...              ...
h1SMnG0035431  h1SMnG0035431  Gene Expression
h1SMnG0035439  h1SMnG0035439  Gene Expression
h1SMnG0035546  h1SMnG0035546  Gene Expression
h1SMnG0035596  h1SMnG0035596  Gene Expression
h1SMnG0035601  h1SMnG0035601  Gene Expression

[44327 rows x 2 columns]

In [11]:
adata_u.obs

Empty DataFrame
Columns: []
Index: [L43_1_AACCATTGGAGACTAGTAACGCTCGA, L43_1_CATTCGACGGAGATCGCACGCTGATC, L43_1_TCGGCCTTACACAGCAGAGAGCTGAA, L43_1_ACGGAGGCGGTGGAACAATAGGATGA, L43_1_GACCTTGATAACGCTCGACAAGACTA, L43_1_TTACCTCGACTGGAACAAAGATCGCA, L43_1_ACCTGGCCAAAGCACCTCAACGCTTA, L43_1_TTACCTCGACCAGCGTTAGAACAGGC, L43_1_ATCATATTAGCAAGACTACCTCTATC, L43_1_TCCTACCAGTCAAGACTATGGAACAA, L43_1_ATAAGGAGCAGCCAAGACCTGAGCCA, L43_1_TCCAATCATCAACCGAGACCGACAAC, L43_1_TCTGATACCAATTGGCTCCATACCAA, L43_1_GGCAGACGCCTGGCTTCAATTGAGGA, L43_1_ATAAGGAGCATGGCTTCAAACGCTTA, L43_1_GGTACCGGCAAAGGACACAGAGTCAA, L43_1_AAGAAGCTAGCTAAGGTCAACAACCA, L43_1_TAGATCTACTGCTCGGTAAGTGGTCA, L43_1_AAGAAGCTAGATCATTCCCAACCACA, L43_1_TAACTGGTTAAAGACGGAGATAGACA, L43_1_AGGTTAGCATAGATCGCAAATCCGTC, L43_1_GCTGGAACTTACACAGAACCAGTTCA, L43_1_CCGATTCCTGGAGCTGAACAATGGAA, L43_1_AACTAGGCGCAGTCACTAGAGTTAGC, L43_1_TCGCGGTTGGCTGGCATAGCTCGGTA, L43_1_AGAGAAGGTTGCGAGTAACAACCACA, L43_1_TGCCGGCAGAGAATCTGAACATTGGC, L43_1_CAACCGCTAAAATGTTGCATCATTCC, L43_1_GGTATGCTTGTGAAGAGAAACGCTTA, L43_1_TCCAATCATCAAGGACACAAGGTACA, L43_1_AGAACGTCTCAAGGACACAGCAGGAA, L43_1_TTATCCGGATGCCACATACATACCAA, L43_1_TCTGATACCAATTGGCTCAACGCTTA, L43_1_TCTGATACCAACAAGCTACTCAATGA, L43_1_CGGATTAGAACTGTAGCCGATGAATC, L43_1_TTATTCATTCAACGTGATCCGACAAC, L43_1_ACTTAACCTTGACAGTGCATAGCGAC, L43_1_CGGTCAAGAAGGTGCGAATATCAGCA, L43_1_TAGATCTACTAAGGACACCTGAGCCA, L43_1_CATTCAATCAATCATTCCGCTAACGA, L43_1_TGCCGGCAGAAACTCACCATTGAGGA, L43_1_GGTATGCTTGGACAGTGCTGGCTTCA, L43_1_TGGTCAGCCACAACCACAACAGCAGA, L43_1_AGGTTAGTTCTATCAGCAACAAGCTA, L43_1_GGCAGACGCCCATACCAAGTACGCAA, L43_1_AAGCCAGTTAAGTGGTCAGTACGCAA, L43_1_AGAACGTCTCAGTCACTAAGCCATGC, L43_1_GCTGGAACTTGACAGTGCCAAGGAGC, L43_1_TAGATCTACTCAAGGAGCTATCAGCA, L43_1_TGCGGACCTACACTTCGAGCGAGTAA, L43_1_AGAGCTATAAAGCCATGCAGATGTAC, L43_1_GATCTTACGCCTGTAGCCAGGCTAAC, L43_1_TAGAATTAACACACAGAATTCACGCA, L43_1_CGCTCCTAACAACGTGATCGACACAC, L43_1_AGAACGTCTCAGATCGCAGAGCTGAA, L43_1_TCGCTAAGCAATAGCGACCATCAAGT, L43_1_ATCATATTAGCGACACACAGATCGCA, L43_1_AATCGATAATACGCTCGACTGAGCCA, L43_1_CCAGTTCCAACAAGGAGCGCCACATA, L43_1_CGTAGTTACCGAATCTGATAGGATGA, L43_1_GGTACCGGCATTCACGCACAACCACA, L43_1_AATTAAGACTGACAGTGCCGCATACA, L43_1_TCTGATACCACGACACACACAAGCTA, L43_1_ACTATGCAATACAGCAGAAACTCACC, L43_1_CATCTCTGCAACCACTGTTAGGATGA, L43_1_TATATACTAAGTGTTCTACCGTGAGA, L43_1_GCCGCAACGACTCAATGAACATTGGC, L43_1_CCATTATCTAGAATCTGACAGATCTG, L43_1_GCTAACTTGCACTATGCAACAGATTC, L43_1_GATCTTACGCATTGGCTCAACGTGAT, L43_1_CGCTCCTAACTGGCTTCAGATAGACA, L43_1_GGCTCTCTATGTCTGTCAATTGAGGA, L43_1_ACGCGAGATTACGCTCGACACTTCGA, L43_1_CATTCAATCAACAAGCTAACACGACC, L43_1_GCTAACTTGCAACCGAGAGAGTTAGC, L43_1_AGGTTAGCATAGTGGTCAGATGAATC, L43_1_ACGCGAGATTATGCCTAACGACACAC, L43_1_GACCTTGATAAACAACCAAGCACCTC, L43_1_TCTAATAGTAATTGAGGAAAGGTACA, L43_1_CTAACTAGATACACGACCACATTGGC, L43_1_ACTTGCTAGACGAACTTAGAATCTGA, L43_1_GGCTCTCTATCAGCGTTACTCAATGA, L43_1_CTAGTAGTCTATAGCGACAATGTTGC, L43_1_ATCGGCTATCAACGTGATGCCAAGAC, L43_1_TTCGCCTCCAGACTAGTAGTGTTCTA, L43_1_GATCTTACGCGAACAGGCACACAGAA, L43_1_CGCTCCTAACATTGAGGACCATCCTC, L43_1_TTCGCCTCCACGAACTTAAACGTGAT, L43_1_AACTAGGCGCTAGGATGACTGGCATA, L43_1_CAACCGCTAATCTTCACACCATCCTC, L43_1_GGCAGACGCCCCATCCTCGATAGACA, L43_1_TCCAATCATCGAATCTGACAAGACTA, L43_1_GGTATCCGCCCAACCACAGTACGCAA, L43_1_GCCATTCTCCGAGTTAGCCGCTGATC, L43_1_AATCGATAATATCATTCCACTATGCA, L43_1_CCGAGAATCCACCTCCAAAGGCTAAC, L43_1_TCTAATAGTAAGAGTCAACAATGGAA, L43_1_TTGACTTCAGAACTCACCGTGTTCTA, L43_1_TTCGCCTCCACAAGGAGCGGTGCGAA, L43_1_GCTGGAACTTGAATCTGAATAGCGAC, ...]

[95420 rows x 0 columns]

In [12]:
adata_u

AnnData object with n_obs × n_vars = 95420 × 44327
    var: 'gene_ids', 'feature_types'

In [13]:
adata_u.X

<95420x44327 sparse matrix of type '<class 'numpy.float32'>'
	with 12457157 stored elements in Compressed Sparse Row format>

In [14]:
type(adata_u.X)

scipy.sparse.csr.csr_matrix

In [15]:
matrix_u = pd.DataFrame.sparse.from_spmatrix(adata_u.X, index=adata_u.obs.index, columns=adata_u.var.index).astype(int)

In [16]:
matrix_u

,h1SMcG0000001,h1SMcG0000002,h1SMcG0000006,h1SMcG0000008,h1SMcG0000009,h1SMcG0000010,h1SMcG0000011,h1SMcG0000012,h1SMcG0000013,h1SMcG0000014,...,h1SMnG0035129,h1SMnG0035188,h1SMnG0035227,h1SMnG0035258,h1SMnG0035302,h1SMnG0035431,h1SMnG0035439,h1SMnG0035546,h1SMnG0035596,h1SMnG0035601
L43_1_AACCATTGGAGACTAGTAACGCTCGA,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
L43_1_CATTCGACGGAGATCGCACGCTGATC,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
L43_1_TCGGCCTTACACAGCAGAGAGCTGAA,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
L43_1_ACGGAGGCGGTGGAACAATAGGATGA,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
L43_1_GACCTTGATAACGCTCGACAAGACTA,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
L43_5_TCGGCCTTACCGAACTTAAGATGTAC,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
L43_5_CCAGTTCCAATGGAACAAATTGGCTC,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
L43_5_TTCGCCTCCACAAGGAGCAAACATCG,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
L43_5_CCGATTCCTGCCGACAACGATAGACA,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
L43_5_TAGAATTAACCAAGGAGCCGGATTGC,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [17]:
raw = adata.raw.to_adata()

In [18]:
matrix_u.index.isin(raw.obs.index)

array([ True,  True, False, ...,  True, False, False])

In [19]:
matrix_u.loc[raw.obs.index]

,h1SMcG0000001,h1SMcG0000002,h1SMcG0000006,h1SMcG0000008,h1SMcG0000009,h1SMcG0000010,h1SMcG0000011,h1SMcG0000012,h1SMcG0000013,h1SMcG0000014,...,h1SMnG0035129,h1SMnG0035188,h1SMnG0035227,h1SMnG0035258,h1SMnG0035302,h1SMnG0035431,h1SMnG0035439,h1SMnG0035546,h1SMnG0035596,h1SMnG0035601
L43_1_AACCATTGGAGACTAGTAACGCTCGA,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
L43_1_CATTCGACGGAGATCGCACGCTGATC,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
L43_1_ACGGAGGCGGTGGAACAATAGGATGA,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
L43_1_GACCTTGATAACGCTCGACAAGACTA,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
L43_1_TTACCTCGACTGGAACAAAGATCGCA,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
L43_5_TAACTGGTTAAAGGTACAGAGTTAGC,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
L43_5_GGTACCGGCAGAATCTGATGAAGAGA,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
L43_5_GCCGCAACGACCAGTTCAAGCAGGAA,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
L43_5_CCAGTTCCAATGGAACAAATTGGCTC,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
L43_5_TTCGCCTCCACAAGGAGCAAACATCG,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [20]:
matrix_dge = matrix_u.loc[raw.obs.index]

In [21]:
matrix_dge

,h1SMcG0000001,h1SMcG0000002,h1SMcG0000006,h1SMcG0000008,h1SMcG0000009,h1SMcG0000010,h1SMcG0000011,h1SMcG0000012,h1SMcG0000013,h1SMcG0000014,...,h1SMnG0035129,h1SMnG0035188,h1SMnG0035227,h1SMnG0035258,h1SMnG0035302,h1SMnG0035431,h1SMnG0035439,h1SMnG0035546,h1SMnG0035596,h1SMnG0035601
L43_1_AACCATTGGAGACTAGTAACGCTCGA,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
L43_1_CATTCGACGGAGATCGCACGCTGATC,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
L43_1_ACGGAGGCGGTGGAACAATAGGATGA,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
L43_1_GACCTTGATAACGCTCGACAAGACTA,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
L43_1_TTACCTCGACTGGAACAAAGATCGCA,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
L43_5_TAACTGGTTAAAGGTACAGAGTTAGC,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
L43_5_GGTACCGGCAGAATCTGATGAAGAGA,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
L43_5_GCCGCAACGACCAGTTCAAGCAGGAA,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
L43_5_CCAGTTCCAATGGAACAAATTGGCTC,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
L43_5_TTCGCCTCCACAAGGAGCAAACATCG,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [22]:
identities_dge = adata.obs

In [23]:
identities_dge

,sample,biological_rep,technical_rep,library,sample_bio,unique,sample_rep,unique_rep,n_counts,n_genes,...,pct_counts_mt,leiden_1,leiden_2,leiden_3,leiden_4,ingest_names,transferred,leiden_3_names_collapsed,leiden_3_names,broad_names
L43_1_AACCATTGGAGACTAGTAACGCTCGA,gfp(RNAi),B2,T2,Lib1,gfp(RNAi)_B2,gfp(RNAi)_Lib1,gfp(RNAi)_B2_T2,gfp(RNAi)_B2_T2_Lib1,148.000,130,...,0.000,8,9,7,25,pgrn+ parenchymal cells 1,pgrn+ parenchymal cells 1,pgrn+ parenchymal cells 1,pgrn+ parenchymal cells 1,parenchymal
L43_1_CATTCGACGGAGATCGCACGCTGATC,gfp(RNAi),B2,T2,Lib1,gfp(RNAi)_B2,gfp(RNAi)_Lib1,gfp(RNAi)_B2_T2,gfp(RNAi)_B2_T2_Lib1,176.000,159,...,0.000,1,1,1,0,chat+ neurons 1,chat+ neurons 1,chat+ neurons 1,chat+ neurons 1,neurons
L43_1_ACGGAGGCGGTGGAACAATAGGATGA,gfp(RNAi),B2,T1,Lib1,gfp(RNAi)_B2,gfp(RNAi)_Lib1,gfp(RNAi)_B2_T1,gfp(RNAi)_B2_T1_Lib1,502.000,359,...,0.000,0,0,0,7,neoblasts 1,neoblasts 1,neoblasts,neoblasts 1,neoblasts
L43_1_GACCTTGATAACGCTCGACAAGACTA,gfp(RNAi),B2,T2,Lib1,gfp(RNAi)_B2,gfp(RNAi)_Lib1,gfp(RNAi)_B2_T2,gfp(RNAi)_B2_T2_Lib1,185.000,149,...,0.000,4,3,9,5,early epidermal progenitors,early epidermal progenitors,early epidermal progenitors 1,early epidermal progenitors 1,epidermal
L43_1_TTACCTCGACTGGAACAAAGATCGCA,lhx1/5-1(RNAi),B1,T2,Lib1,lhx1/5-1(RNAi)_B1,lhx1/5-1(RNAi)_Lib1,lhx1/5-1(RNAi)_B1_T2,lhx1/5-1(RNAi)_B1_T2_Lib1,180.000,166,...,0.000,2,6,3,9,intestinal and DV muscle,intestinal and DV muscle,intestinal and DV muscle,intestinal and DV muscle,muscle
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
L43_5_TAACTGGTTAAAGGTACAGAGTTAGC,gfp(RNAi),B2,T2,Lib5,gfp(RNAi)_B2,gfp(RNAi)_Lib5,gfp(RNAi)_B2_T2,gfp(RNAi)_B2_T2_Lib5,411.000,212,...,0.000,7,37,26,49,epidermis,epidermis,epidermis 2,epidermis 2,epidermal
L43_5_GGTACCGGCAGAATCTGATGAAGAGA,gfp(RNAi),B2,T2,Lib5,gfp(RNAi)_B2,gfp(RNAi)_Lib5,gfp(RNAi)_B2_T2,gfp(RNAi)_B2_T2_Lib5,262.000,186,...,0.000,0,0,5,4,neoblasts 1,neoblasts 1,neoblasts,neoblasts 3,neoblasts
L43_5_GCCGCAACGACCAGTTCAAGCAGGAA,gfp(RNAi),B1,T2,Lib5,gfp(RNAi)_B1,gfp(RNAi)_Lib5,gfp(RNAi)_B1_T2,gfp(RNAi)_B1_T2_Lib5,110.000,103,...,0.000,5,8,6,3,pgrn+ parenchymal cells 2,pgrn+ parenchymal cells 2,pgrn+ parenchymal cells 2,pgrn+ parenchymal cells 2,parenchymal
L43_5_CCAGTTCCAATGGAACAAATTGGCTC,gfp(RNAi),B2,T1,Lib5,gfp(RNAi)_B2,gfp(RNAi)_Lib5,gfp(RNAi)_B2_T1,gfp(RNAi)_B2_T1_Lib5,238.000,201,...,0.000,1,1,1,0,chat+ neurons 1,chat+ neurons 1,chat+ neurons 1,chat+ neurons 1,neurons
L43_5_TTCGCCTCCACAAGGAGCAAACATCG,lhx1/5-1(RNAi),B1,T2,Lib5,lhx1/5-1(RNAi)_B1,lhx1/5-1(RNAi)_Lib5,lhx1/5-1(RNAi)_B1_T2,lhx1/5-1(RNAi)_B1_T2_Lib5,230.000,138,...,0.000,3,33,38,43,committed neoblasts,neoblasts 1,neoblasts,neoblasts 4,neoblasts

In [34]:
genes_dge = adata.var

In [35]:
genes_dge

,gene_ids,feature_types,longest_isoform,gene_type,gene_JakkeGuo,gene_Jakke_ver1,gene_ddv6,jakkeguo_collapsed,jakke_ver1_collapsed,ddv6_collapsed,...,n_cells_by_counts,mean_counts,pct_dropout_by_counts,total_counts,highly_variable,means,dispersions,dispersions_norm,mean,std
h1SMcG0000008,h1SMcG0000008,Gene Expression,h1SMcT0000008.1,hconf,SMEST029651001.1,SMEST029651001.1,dd_Smed_v6_35379_0_1,"SMEST029651001.1,SMEST029651002.1,SmMSTRG.9911...","SMEST029651001.1,SMEST029651002.1",dd_Smed_v6_35379_0_1,...,10,0.000,99.979,11.000,True,0.000,0.478,1.456,0.000,0.013
h1SMcG0000009,h1SMcG0000009,Gene Expression,h1SMcT0000009.2,hconf,SMEST029652002.1,SMEST029652002.1,dd_Smed_v6_5323_0_1,"SMEST029652002.1,SmMSTRG.9914.2,SmMSTRG.9914.3...",SMEST029652002.1,dd_Smed_v6_5323_0_1,...,196,0.004,99.586,197.000,True,0.003,0.036,0.147,0.002,0.039
h1SMcG0000011,h1SMcG0000011,Gene Expression,h1SMcT0000011.1,hconf,SMEST029655001.1,SMEST029655001.1,dd_Smed_v6_6416_0_1,"SMEST029655001.1,SMEST029655002.1,SmMSTRG.9916...","SMEST029655001.1,SMEST029655002.1",dd_Smed_v6_6416_0_1,...,2366,0.053,95.005,"2,525.000",True,0.045,0.141,0.456,0.031,0.146
h1SMcG0000012,h1SMcG0000012,Gene Expression,h1SMcT0000012.1,hconf,SmMSTRG.9913.2,SMEST029666001.1,dd_Smed_v6_20296_0_1,"SMEST029666001.1,SmMSTRG.9913.2",SMEST029666001.1,dd_Smed_v6_20296_0_1,...,25,0.001,99.947,26.000,True,0.000,0.186,0.590,0.000,0.015
h1SMcG0000013,h1SMcG0000013,Gene Expression,h1SMcT0000013.5,hconf,SmMSTRG.9917.1,MSTRG.9917.1,dd_Smed_v6_4708_0_1,"SMEST029667004.1,SmMSTRG.9917.1,SmMSTRG.9917.2...","MSTRG.9917.1,SMEST029667004.1",dd_Smed_v6_4708_0_1,...,681,0.015,98.562,705.000,True,0.013,0.100,0.336,0.009,0.077
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
h1SMnG0034970,h1SMnG0034970,Gene Expression,h1SMnT0034970.1,other,-,-,-,-,-,-,...,2,0.000,99.996,2.000,True,0.000,0.120,0.396,0.000,0.004
h1SMnG0035064,h1SMnG0035064,Gene Expression,h1SMnT0035064.1,other,-,-,-,-,-,-,...,1,0.000,99.998,1.000,True,0.000,0.226,0.708,0.000,0.004
h1SMnG0035227,h1SMnG0035227,Gene Expression,h1SMnT0035227.1,other,-,-,-,-,-,-,...,2,0.000,99.996,2.000,True,0.000,0.321,0.992,0.000,0.005
h1SMnG0035258,h1SMnG0035258,Gene Expression,h1SMnT0035258.1,hconf,-,-,-,-,-,-,...,3,0.000,99.994,3.000,True,0.000,0.376,1.152,0.000,0.007
h1SMnG0035302,h1SMnG0035302,Gene Expression,h1SMnT0035302.1,other,-,-,-,-,-,-,...,2,0.000,99.996,2.000,True,0.000,0.086,0.294,0.000,0.005

In [24]:
from scipy.sparse import csr_matrix

In [25]:
sparse_matrix = csr_matrix(matrix_dge.values)

In [26]:
from scipy.io import mmwrite

In [27]:
file_path = './outputs/06092023_smed_sero_matrix.mtx'

In [28]:
mmwrite(file_path, sparse_matrix)

In [30]:
sparse_matrix

<47292x44327 sparse matrix of type '<class 'numpy.intc'>'
	with 9372888 stored elements in Compressed Sparse Row format>

In [31]:
print(sparse_matrix)

  (0, 136)	1
  (0, 414)	1
  (0, 519)	1
  (0, 740)	1
  (0, 823)	1
  (0, 1018)	1
  (0, 1178)	1
  (0, 1560)	3
  (0, 1694)	1
  (0, 1907)	1
  (0, 1994)	1
  (0, 2275)	1
  (0, 2488)	1
  (0, 2495)	2
  (0, 2514)	1
  (0, 2583)	1
  (0, 2714)	1
  (0, 2756)	1
  (0, 2803)	1
  (0, 2864)	1
  (0, 3033)	1
  (0, 3061)	1
  (0, 3254)	1
  (0, 3403)	1
  (0, 3480)	1
  :	:
  (47291, 20615)	1
  (47291, 20733)	1
  (47291, 21339)	1
  (47291, 23127)	1
  (47291, 23625)	1
  (47291, 23905)	1
  (47291, 25327)	1
  (47291, 26213)	1
  (47291, 26630)	1
  (47291, 28390)	1
  (47291, 28504)	1
  (47291, 28728)	1
  (47291, 30427)	1
  (47291, 31447)	1
  (47291, 32367)	1
  (47291, 32553)	1
  (47291, 32999)	2
  (47291, 33347)	2
  (47291, 33959)	1
  (47291, 34194)	2
  (47291, 34205)	1
  (47291, 34293)	1
  (47291, 35382)	2
  (47291, 35575)	67
  (47291, 35578)	1

In [32]:
column_names = matrix_dge.columns.tolist()
with open('./outputs/column_names_matrix.txt', 'w') as f:
    f.write('\n'.join(column_names))

In [33]:
column_names

['h1SMcG0000001',
 'h1SMcG0000002',
 'h1SMcG0000006',
 'h1SMcG0000008',
 'h1SMcG0000009',
 'h1SMcG0000010',
 'h1SMcG0000011',
 'h1SMcG0000012',
 'h1SMcG0000013',
 'h1SMcG0000014',
 'h1SMcG0000015',
 'h1SMcG0000016',
 'h1SMcG0000017',
 'h1SMcG0000018',
 'h1SMcG0000020',
 'h1SMcG0000021',
 'h1SMcG0000022',
 'h1SMcG0000023',
 'h1SMcG0000024',
 'h1SMcG0000025',
 'h1SMcG0000026',
 'h1SMcG0000027',
 'h1SMcG0000028',
 'h1SMcG0000029',
 'h1SMcG0000030',
 'h1SMcG0000031',
 'h1SMcG0000032',
 'h1SMcG0000033',
 'h1SMcG0000034',
 'h1SMcG0000035',
 'h1SMcG0000036',
 'h1SMcG0000039',
 'h1SMcG0000040',
 'h1SMcG0000041',
 'h1SMcG0000042',
 'h1SMcG0000043',
 'h1SMcG0000044',
 'h1SMcG0000045',
 'h1SMcG0000046',
 'h1SMcG0000047',
 'h1SMcG0000048',
 'h1SMcG0000049',
 'h1SMcG0000050',
 'h1SMcG0000052',
 'h1SMcG0000053',
 'h1SMcG0000054',
 'h1SMcG0000056',
 'h1SMcG0000057',
 'h1SMcG0000058',
 'h1SMcG0000059',
 'h1SMcG0000060',
 'h1SMcG0000062',
 'h1SMcG0000064',
 'h1SMcG0000065',
 'h1SMcG0000066',
 'h1SMcG0000067',
 'h1SMcG0000068',
 'h1SMcG0000069',
 'h1SMcG0000070',
 'h1SMcG0000071',
 'h1SMcG0000073',
 'h1SMcG0000075',
 'h1SMcG0000076',
 'h1SMcG0000078',
 'h1SMcG0000079',
 'h1SMcG0000080',
 'h1SMcG0000081',
 'h1SMcG0000082',
 'h1SMcG0000083',
 'h1SMcG0000084',
 'h1SMcG0000085',
 'h1SMcG0000086',
 'h1SMcG0000087',
 'h1SMcG0000089',
 'h1SMcG0000090',
 'h1SMcG0000092',
 'h1SMcG0000093',
 'h1SMcG0000094',
 'h1SMcG0000095',
 'h1SMcG0000096',
 'h1SMcG0000097',
 'h1SMcG0000098',
 'h1SMcG0000100',
 'h1SMcG0000101',
 'h1SMcG0000102',
 'h1SMcG0000103',
 'h1SMcG0000104',
 'h1SMcG0000105',
 'h1SMcG0000106',
 'h1SMcG0000107',
 'h1SMcG0000109',
 'h1SMcG0000110',
 'h1SMcG0000111',
 'h1SMcG0000113',
 'h1SMcG0000114',
 'h1SMcG0000115',
 'h1SMcG0000116',
 'h1SMcG0000117',
 'h1SMcG0000120',
 'h1SMcG0000122',
 'h1SMcG0000123',
 'h1SMcG0000124',
 'h1SMcG0000125',
 'h1SMcG0000127',
 'h1SMcG0000128',
 'h1SMcG0000130',
 'h1SMcG0000131',
 'h1SMcG0000132',
 'h1SMcG0000133',
 'h1SMcG0000134',
 'h1SMcG0000135',
 'h1SMcG0000136',
 'h1SMcG0000137',
 'h1SMcG0000141',
 'h1SMcG0000143',
 'h1SMcG0000144',
 'h1SMcG0000145',
 'h1SMcG0000146',
 'h1SMcG0000147',
 'h1SMcG0000148',
 'h1SMcG0000149',
 'h1SMcG0000150',
 'h1SMcG0000151',
 'h1SMcG0000152',
 'h1SMcG0000153',
 'h1SMcG0000154',
 'h1SMcG0000155',
 'h1SMcG0000156',
 'h1SMcG0000157',
 'h1SMcG0000158',
 'h1SMcG0000159',
 'h1SMcG0000160',
 'h1SMcG0000162',
 'h1SMcG0000163',
 'h1SMcG0000165',
 'h1SMcG0000169',
 'h1SMcG0000170',
 'h1SMcG0000171',
 'h1SMcG0000173',
 'h1SMcG0000174',
 'h1SMcG0000175',
 'h1SMcG0000176',
 'h1SMcG0000177',
 'h1SMcG0000178',
 'h1SMcG0000180',
 'h1SMcG0000181',
 'h1SMcG0000182',
 'h1SMcG0000183',
 'h1SMcG0000186',
 'h1SMcG0000187',
 'h1SMcG0000188',
 'h1SMcG0000189',
 'h1SMcG0000190',
 'h1SMcG0000191',
 'h1SMcG0000193',
 'h1SMcG0000194',
 'h1SMcG0000195',
 'h1SMcG0000196',
 'h1SMcG0000199',
 'h1SMcG0000201',
 'h1SMcG0000202',
 'h1SMcG0000204',
 'h1SMcG0000207',
 'h1SMcG0000208',
 'h1SMcG0000209',
 'h1SMcG0000211',
 'h1SMcG0000212',
 'h1SMcG0000215',
 'h1SMcG0000216',
 'h1SMcG0000218',
 'h1SMcG0000219',
 'h1SMcG0000221',
 'h1SMcG0000224',
 'h1SMcG0000226',
 'h1SMcG0000227',
 'h1SMcG0000228',
 'h1SMcG0000229',
 'h1SMcG0000231',
 'h1SMcG0000232',
 'h1SMcG0000234',
 'h1SMcG0000235',
 'h1SMcG0000236',
 'h1SMcG0000237',
 'h1SMcG0000238',
 'h1SMcG0000239',
 'h1SMcG0000240',
 'h1SMcG0000241',
 'h1SMcG0000242',
 'h1SMcG0000243',
 'h1SMcG0000245',
 'h1SMcG0000246',
 'h1SMcG0000248',
 'h1SMcG0000250',
 'h1SMcG0000251',
 'h1SMcG0000252',
 'h1SMcG0000253',
 'h1SMcG0000254',
 'h1SMcG0000255',
 'h1SMcG0000256',
 'h1SMcG0000257',
 'h1SMcG0000258',
 'h1SMcG0000262',
 'h1SMcG0000263',
 'h1SMcG0000264',
 'h1SMcG0000265',
 'h1SMcG0000266',
 'h1SMcG0000270',
 'h1SMcG0000273',
 'h1SMcG0000274',
 'h1SMcG0000275',
 'h1SMcG0000280',
 'h1SMcG0000281',
 'h1SMcG0000282',
 'h1SMcG0000283',
 'h1SMcG0000284',
 'h1SMcG0000285',
 'h1SMcG0000286',
 'h1SMcG0000287',
 'h1SMcG0000288',
 'h1SMcG0000290',
 'h1SMcG0000292',
 'h1SMcG0000293',
 'h1SMcG0000295',
 'h1SMcG0000296',
 'h1SMcG0000297',
 'h1SMcG0000299',
 'h1SMcG0000300',
 'h1SMcG0000301',
 'h1SMcG0000302',
 'h1SMcG0000305',
 'h1SMcG0000311',
 'h1SMcG0000318',
 'h1SMcG0000319',
 'h1SMcG0000320',
 'h1SMcG0000321',
 'h1SMcG0000322',
 'h1SMcG0000323',
 'h1SMcG0000325',
 'h1SMcG0000327',
 'h1SMcG0000328',
 'h1SMcG0000329',
 'h1SMcG0000330',
 'h1SMcG0000332',
 'h1SMcG0000333',
 'h1SMcG0000334',
 'h1SMcG0000337',
 'h1SMcG0000338',
 'h1SMcG0000340',
 'h1SMcG0000341',
 'h1SMcG0000342',
 'h1SMcG0000343',
 'h1SMcG0000345',
 'h1SMcG0000347',
 'h1SMcG0000349',
 'h1SMcG0000350',
 'h1SMcG0000352',
 'h1SMcG0000353',
 'h1SMcG0000355',
 'h1SMcG0000357',
 'h1SMcG0000358',
 'h1SMcG0000359',
 'h1SMcG0000360',
 'h1SMcG0000362',
 'h1SMcG0000363',
 'h1SMcG0000364',
 'h1SMcG0000365',
 'h1SMcG0000366',
 'h1SMcG0000368',
 'h1SMcG0000369',
 'h1SMcG0000371',
 'h1SMcG0000372',
 'h1SMcG0000374',
 'h1SMcG0000375',
 'h1SMcG0000377',
 'h1SMcG0000378',
 'h1SMcG0000379',
 'h1SMcG0000380',
 'h1SMcG0000381',
 'h1SMcG0000382',
 'h1SMcG0000383',
 'h1SMcG0000384',
 'h1SMcG0000387',
 'h1SMcG0000388',
 'h1SMcG0000389',
 'h1SMcG0000390',
 'h1SMcG0000391',
 'h1SMcG0000392',
 'h1SMcG0000394',
 'h1SMcG0000396',
 'h1SMcG0000400',
 'h1SMcG0000401',
 'h1SMcG0000403',
 'h1SMcG0000404',
 'h1SMcG0000405',
 'h1SMcG0000406',
 'h1SMcG0000407',
 'h1SMcG0000408',
 'h1SMcG0000409',
 'h1SMcG0000410',
 'h1SMcG0000411',
 'h1SMcG0000413',
 'h1SMcG0000414',
 'h1SMcG0000415',
 'h1SMcG0000417',
 'h1SMcG0000419',
 'h1SMcG0000420',
 'h1SMcG0000421',
 'h1SMcG0000423',
 'h1SMcG0000424',
 'h1SMcG0000425',
 'h1SMcG0000426',
 'h1SMcG0000427',
 'h1SMcG0000428',
 'h1SMcG0000429',
 'h1SMcG0000430',
 'h1SMcG0000431',
 'h1SMcG0000432',
 'h1SMcG0000433',
 'h1SMcG0000434',
 'h1SMcG0000435',
 'h1SMcG0000437',
 'h1SMcG0000438',
 'h1SMcG0000439',
 'h1SMcG0000440',
 'h1SMcG0000442',
 'h1SMcG0000443',
 'h1SMcG0000444',
 'h1SMcG0000445',
 'h1SMcG0000446',
 'h1SMcG0000447',
 'h1SMcG0000448',
 'h1SMcG0000449',
 'h1SMcG0000452',
 'h1SMcG0000453',
 'h1SMcG0000454',
 'h1SMcG0000455',
 'h1SMcG0000456',
 'h1SMcG0000457',
 'h1SMcG0000458',
 'h1SMcG0000459',
 'h1SMcG0000460',
 'h1SMcG0000462',
 'h1SMcG0000463',
 'h1SMcG0000466',
 'h1SMcG0000468',
 'h1SMcG0000470',
 'h1SMcG0000471',
 'h1SMcG0000472',
 'h1SMcG0000473',
 'h1SMcG0000474',
 'h1SMcG0000476',
 'h1SMcG0000477',
 'h1SMcG0000478',
 'h1SMcG0000479',
 'h1SMcG0000480',
 'h1SMcG0000481',
 'h1SMcG0000482',
 'h1SMcG0000483',
 'h1SMcG0000485',
 'h1SMcG0000486',
 'h1SMcG0000487',
 'h1SMcG0000488',
 'h1SMcG0000489',
 'h1SMcG0000490',
 'h1SMcG0000491',
 'h1SMcG0000492',
 'h1SMcG0000493',
 'h1SMcG0000494',
 'h1SMcG0000495',
 'h1SMcG0000496',
 'h1SMcG0000497',
 'h1SMcG0000499',
 'h1SMcG0000500',
 'h1SMcG0000501',
 'h1SMcG0000502',
 'h1SMcG0000503',
 'h1SMcG0000504',
 'h1SMcG0000505',
 'h1SMcG0000506',
 'h1SMcG0000507',
 'h1SMcG0000508',
 'h1SMcG0000510',
 'h1SMcG0000511',
 'h1SMcG0000512',
 'h1SMcG0000513',
 'h1SMcG0000514',
 'h1SMcG0000515',
 'h1SMcG0000516',
 'h1SMcG0000517',
 'h1SMcG0000518',
 'h1SMcG0000519',
 'h1SMcG0000520',
 'h1SMcG0000522',
 'h1SMcG0000523',
 'h1SMcG0000524',
 'h1SMcG0000525',
 'h1SMcG0000526',
 'h1SMcG0000527',
 'h1SMcG0000528',
 'h1SMcG0000530',
 'h1SMcG0000531',
 'h1SMcG0000532',
 'h1SMcG0000533',
 'h1SMcG0000534',
 'h1SMcG0000536',
 'h1SMcG0000538',
 'h1SMcG0000541',
 'h1SMcG0000542',
 'h1SMcG0000543',
 'h1SMcG0000544',
 'h1SMcG0000545',
 'h1SMcG0000546',
 'h1SMcG0000547',
 'h1SMcG0000548',
 'h1SMcG0000549',
 'h1SMcG0000550',
 'h1SMcG0000551',
 'h1SMcG0000554',
 'h1SMcG0000556',
 'h1SMcG0000558',
 'h1SMcG0000559',
 'h1SMcG0000560',
 'h1SMcG0000561',
 'h1SMcG0000562',
 'h1SMcG0000564',
 'h1SMcG0000565',
 'h1SMcG0000566',
 'h1SMcG0000567',
 'h1SMcG0000569',
 'h1SMcG0000570',
 'h1SMcG0000571',
 'h1SMcG0000572',
 'h1SMcG0000574',
 'h1SMcG0000576',
 'h1SMcG0000577',
 'h1SMcG0000579',
 'h1SMcG0000581',
 'h1SMcG0000582',
 'h1SMcG0000583',
 'h1SMcG0000584',
 'h1SMcG0000585',
 'h1SMcG0000586',
 'h1SMcG0000587',
 'h1SMcG0000588',
 'h1SMcG0000589',
 'h1SMcG0000590',
 'h1SMcG0000591',
 'h1SMcG0000592',
 'h1SMcG0000593',
 'h1SMcG0000595',
 'h1SMcG0000596',
 'h1SMcG0000597',
 'h1SMcG0000598',
 'h1SMcG0000599',
 'h1SMcG0000600',
 'h1SMcG0000601',
 'h1SMcG0000602',
 'h1SMcG0000604',
 'h1SMcG0000609',
 'h1SMcG0000612',
 'h1SMcG0000613',
 'h1SMcG0000614',
 'h1SMcG0000615',
 'h1SMcG0000616',
 'h1SMcG0000617',
 'h1SMcG0000618',
 'h1SMcG0000619',
 'h1SMcG0000620',
 'h1SMcG0000621',
 'h1SMcG0000622',
 'h1SMcG0000623',
 'h1SMcG0000626',
 'h1SMcG0000627',
 'h1SMcG0000628',
 'h1SMcG0000630',
 'h1SMcG0000631',
 'h1SMcG0000633',
 'h1SMcG0000634',
 'h1SMcG0000635',
 'h1SMcG0000636',
 'h1SMcG0000637',
 'h1SMcG0000639',
 'h1SMcG0000640',
 'h1SMcG0000641',
 'h1SMcG0000643',
 'h1SMcG0000644',
 'h1SMcG0000645',
 'h1SMcG0000646',
 'h1SMcG0000647',
 'h1SMcG0000648',
 'h1SMcG0000649',
 'h1SMcG0000651',
 'h1SMcG0000652',
 'h1SMcG0000653',
 'h1SMcG0000654',
 'h1SMcG0000655',
 'h1SMcG0000656',
 'h1SMcG0000657',
 'h1SMcG0000658',
 'h1SMcG0000659',
 'h1SMcG0000660',
 'h1SMcG0000661',
 'h1SMcG0000662',
 'h1SMcG0000664',
 'h1SMcG0000665',
 'h1SMcG0000666',
 'h1SMcG0000667',
 'h1SMcG0000668',
 'h1SMcG0000669',
 'h1SMcG0000670',
 'h1SMcG0000671',
 'h1SMcG0000673',
 'h1SMcG0000674',
 'h1SMcG0000675',
 'h1SMcG0000677',
 'h1SMcG0000678',
 'h1SMcG0000679',
 'h1SMcG0000680',
 'h1SMcG0000682',
 'h1SMcG0000684',
 'h1SMcG0000686',
 'h1SMcG0000687',
 'h1SMcG0000688',
 'h1SMcG0000689',
 'h1SMcG0000690',
 'h1SMcG0000692',
 'h1SMcG0000695',
 'h1SMcG0000696',
 'h1SMcG0000697',
 'h1SMcG0000698',
 'h1SMcG0000699',
 'h1SMcG0000700',
 'h1SMcG0000701',
 'h1SMcG0000702',
 'h1SMcG0000703',
 'h1SMcG0000704',
 'h1SMcG0000705',
 'h1SMcG0000706',
 'h1SMcG0000707',
 'h1SMcG0000708',
 'h1SMcG0000709',
 'h1SMcG0000710',
 'h1SMcG0000711',
 'h1SMcG0000716',
 'h1SMcG0000718',
 'h1SMcG0000719',
 'h1SMcG0000720',
 'h1SMcG0000721',
 'h1SMcG0000723',
 'h1SMcG0000726',
 'h1SMcG0000727',
 'h1SMcG0000728',
 'h1SMcG0000729',
 'h1SMcG0000730',
 'h1SMcG0000736',
 'h1SMcG0000737',
 'h1SMcG0000738',
 'h1SMcG0000739',
 'h1SMcG0000740',
 'h1SMcG0000741',
 'h1SMcG0000742',
 'h1SMcG0000743',
 'h1SMcG0000744',
 'h1SMcG0000745',
 'h1SMcG0000746',
 'h1SMcG0000747',
 'h1SMcG0000748',
 'h1SMcG0000749',
 'h1SMcG0000750',
 'h1SMcG0000751',
 'h1SMcG0000752',
 'h1SMcG0000753',
 'h1SMcG0000754',
 'h1SMcG0000756',
 'h1SMcG0000757',
 'h1SMcG0000758',
 'h1SMcG0000759',
 'h1SMcG0000761',
 'h1SMcG0000763',
 'h1SMcG0000764',
 'h1SMcG0000765',
 'h1SMcG0000766',
 'h1SMcG0000769',
 'h1SMcG0000770',
 'h1SMcG0000771',
 'h1SMcG0000772',
 'h1SMcG0000773',
 'h1SMcG0000775',
 'h1SMcG0000776',
 'h1SMcG0000777',
 'h1SMcG0000781',
 'h1SMcG0000782',
 'h1SMcG0000783',
 'h1SMcG0000784',
 'h1SMcG0000785',
 'h1SMcG0000787',
 'h1SMcG0000788',
 'h1SMcG0000789',
 'h1SMcG0000790',
 'h1SMcG0000791',
 'h1SMcG0000792',
 'h1SMcG0000794',
 'h1SMcG0000795',
 'h1SMcG0000796',
 'h1SMcG0000797',
 'h1SMcG0000798',
 'h1SMcG0000800',
 'h1SMcG0000801',
 'h1SMcG0000802',
 'h1SMcG0000803',
 'h1SMcG0000804',
 'h1SMcG0000805',
 'h1SMcG0000807',
 'h1SMcG0000808',
 'h1SMcG0000809',
 'h1SMcG0000810',
 'h1SMcG0000811',
 'h1SMcG0000812',
 'h1SMcG0000813',
 'h1SMcG0000815',
 'h1SMcG0000816',
 'h1SMcG0000817',
 'h1SMcG0000818',
 'h1SMcG0000819',
 'h1SMcG0000820',
 'h1SMcG0000821',
 'h1SMcG0000822',
 'h1SMcG0000823',
 'h1SMcG0000825',
 'h1SMcG0000826',
 'h1SMcG0000827',
 'h1SMcG0000829',
 'h1SMcG0000830',
 'h1SMcG0000832',
 'h1SMcG0000835',
 'h1SMcG0000837',
 'h1SMcG0000838',
 'h1SMcG0000839',
 'h1SMcG0000842',
 'h1SMcG0000843',
 'h1SMcG0000844',
 'h1SMcG0000845',
 'h1SMcG0000846',
 'h1SMcG0000849',
 'h1SMcG0000850',
 'h1SMcG0000851',
 'h1SMcG0000852',
 'h1SMcG0000854',
 'h1SMcG0000855',
 'h1SMcG0000856',
 'h1SMcG0000858',
 'h1SMcG0000859',
 'h1SMcG0000860',
 'h1SMcG0000863',
 'h1SMcG0000864',
 'h1SMcG0000866',
 'h1SMcG0000868',
 'h1SMcG0000871',
 'h1SMcG0000872',
 'h1SMcG0000873',
 'h1SMcG0000875',
 'h1SMcG0000877',
 'h1SMcG0000878',
 'h1SMcG0000879',
 'h1SMcG0000880',
 'h1SMcG0000881',
 'h1SMcG0000882',
 'h1SMcG0000883',
 'h1SMcG0000886',
 'h1SMcG0000887',
 'h1SMcG0000888',
 'h1SMcG0000890',
 'h1SMcG0000891',
 'h1SMcG0000892',
 'h1SMcG0000893',
 'h1SMcG0000895',
 'h1SMcG0000896',
 'h1SMcG0000897',
 'h1SMcG0000898',
 'h1SMcG0000899',
 'h1SMcG0000900',
 'h1SMcG0000901',
 'h1SMcG0000902',
 'h1SMcG0000903',
 'h1SMcG0000904',
 'h1SMcG0000905',
 'h1SMcG0000906',
 'h1SMcG0000907',
 'h1SMcG0000908',
 'h1SMcG0000909',
 'h1SMcG0000910',
 'h1SMcG0000913',
 'h1SMcG0000915',
 'h1SMcG0000916',
 'h1SMcG0000917',
 'h1SMcG0000918',
 'h1SMcG0000919',
 'h1SMcG0000920',
 'h1SMcG0000921',
 'h1SMcG0000922',
 'h1SMcG0000924',
 'h1SMcG0000925',
 'h1SMcG0000927',
 'h1SMcG0000928',
 'h1SMcG0000929',
 'h1SMcG0000930',
 'h1SMcG0000932',
 'h1SMcG0000934',
 'h1SMcG0000936',
 'h1SMcG0000937',
 'h1SMcG0000938',
 'h1SMcG0000939',
 'h1SMcG0000941',
 'h1SMcG0000942',
 'h1SMcG0000943',
 'h1SMcG0000944',
 'h1SMcG0000945',
 'h1SMcG0000946',
 'h1SMcG0000947',
 'h1SMcG0000948',
 'h1SMcG0000951',
 'h1SMcG0000952',
 'h1SMcG0000953',
 'h1SMcG0000955',
 'h1SMcG0000957',
 'h1SMcG0000958',
 'h1SMcG0000960',
 'h1SMcG0000961',
 'h1SMcG0000962',
 'h1SMcG0000963',
 'h1SMcG0000964',
 'h1SMcG0000965',
 'h1SMcG0000966',
 'h1SMcG0000967',
 'h1SMcG0000968',
 'h1SMcG0000969',
 'h1SMcG0000971',
 'h1SMcG0000972',
 'h1SMcG0000973',
 'h1SMcG0000974',
 'h1SMcG0000975',
 'h1SMcG0000976',
 'h1SMcG0000977',
 'h1SMcG0000978',
 'h1SMcG0000979',
 'h1SMcG0000980',
 'h1SMcG0000981',
 'h1SMcG0000986',
 'h1SMcG0000988',
 'h1SMcG0000989',
 'h1SMcG0000990',
 'h1SMcG0000991',
 'h1SMcG0000992',
 'h1SMcG0000995',
 'h1SMcG0000997',
 'h1SMcG0000998',
 'h1SMcG0000999',
 'h1SMcG0001002',
 'h1SMcG0001005',
 'h1SMcG0001006',
 'h1SMcG0001007',
 'h1SMcG0001008',
 'h1SMcG0001009',
 'h1SMcG0001010',
 'h1SMcG0001011',
 'h1SMcG0001012',
 'h1SMcG0001013',
 'h1SMcG0001014',
 'h1SMcG0001015',
 'h1SMcG0001016',
 'h1SMcG0001017',
 'h1SMcG0001018',
 'h1SMcG0001019',
 'h1SMcG0001020',
 'h1SMcG0001021',
 'h1SMcG0001022',
 'h1SMcG0001023',
 'h1SMcG0001025',
 'h1SMcG0001026',
 'h1SMcG0001027',
 'h1SMcG0001028',
 'h1SMcG0001029',
 'h1SMcG0001030',
 'h1SMcG0001031',
 'h1SMcG0001032',
 'h1SMcG0001033',
 'h1SMcG0001034',
 'h1SMcG0001035',
 'h1SMcG0001036',
 'h1SMcG0001037',
 'h1SMcG0001039',
 'h1SMcG0001040',
 'h1SMcG0001041',
 'h1SMcG0001042',
 'h1SMcG0001043',
 'h1SMcG0001044',
 'h1SMcG0001045',
 'h1SMcG0001047',
 'h1SMcG0001048',
 'h1SMcG0001049',
 'h1SMcG0001050',
 'h1SMcG0001052',
 'h1SMcG0001053',
 'h1SMcG0001054',
 'h1SMcG0001056',
 'h1SMcG0001057',
 'h1SMcG0001058',
 'h1SMcG0001059',
 'h1SMcG0001060',
 'h1SMcG0001061',
 'h1SMcG0001063',
 'h1SMcG0001064',
 'h1SMcG0001065',
 'h1SMcG0001066',
 'h1SMcG0001067',
 'h1SMcG0001068',
 'h1SMcG0001069',
 'h1SMcG0001071',
 'h1SMcG0001072',
 'h1SMcG0001073',
 'h1SMcG0001074',
 'h1SMcG0001075',
 'h1SMcG0001077',
 'h1SMcG0001078',
 'h1SMcG0001080',
 'h1SMcG0001081',
 'h1SMcG0001082',
 'h1SMcG0001083',
 'h1SMcG0001084',
 'h1SMcG0001085',
 'h1SMcG0001086',
 'h1SMcG0001088',
 'h1SMcG0001089',
 'h1SMcG0001092',
 'h1SMcG0001093',
 'h1SMcG0001094',
 'h1SMcG0001097',
 'h1SMcG0001098',
 'h1SMcG0001100',
 'h1SMcG0001101',
 'h1SMcG0001102',
 'h1SMcG0001103',
 'h1SMcG0001104',
 'h1SMcG0001105',
 'h1SMcG0001107',
 'h1SMcG0001108',
 'h1SMcG0001109',
 'h1SMcG0001110',
 'h1SMcG0001112',
 'h1SMcG0001113',
 'h1SMcG0001114',
 'h1SMcG0001115',
 'h1SMcG0001116',
 'h1SMcG0001117',
 'h1SMcG0001118',
 'h1SMcG0001119',
 'h1SMcG0001120',
 'h1SMcG0001121',
 'h1SMcG0001122',
 'h1SMcG0001123',
 'h1SMcG0001124',
 'h1SMcG0001125',
 'h1SMcG0001126',
 'h1SMcG0001127',
 'h1SMcG0001128',
 'h1SMcG0001129',
 'h1SMcG0001130',
 'h1SMcG0001131',
 'h1SMcG0001132',
 'h1SMcG0001133',
 'h1SMcG0001134',
 'h1SMcG0001135',
 'h1SMcG0001136',
 'h1SMcG0001137',
 'h1SMcG0001138',
 'h1SMcG0001139',
 'h1SMcG0001140',
 'h1SMcG0001141',
 'h1SMcG0001142',
 'h1SMcG0001144',
 'h1SMcG0001145',
 'h1SMcG0001148',
 'h1SMcG0001149',
 'h1SMcG0001151',
 'h1SMcG0001152',
 'h1SMcG0001153',
 'h1SMcG0001154',
 'h1SMcG0001155',
 'h1SMcG0001156',
 'h1SMcG0001157',
 'h1SMcG0001158',
 'h1SMcG0001159',
 'h1SMcG0001160',
 'h1SMcG0001161',
 'h1SMcG0001162',
 'h1SMcG0001163',
 'h1SMcG0001165',
 'h1SMcG0001166',
 'h1SMcG0001167',
 'h1SMcG0001169',
 'h1SMcG0001170',
 'h1SMcG0001171',
 'h1SMcG0001172',
 'h1SMcG0001173',
 'h1SMcG0001174',
 'h1SMcG0001175',
 'h1SMcG0001177',
 'h1SMcG0001178',
 'h1SMcG0001180',
 'h1SMcG0001181',
 'h1SMcG0001182',
 'h1SMcG0001183',
 'h1SMcG0001184',
 'h1SMcG0001185',
 'h1SMcG0001186',
 'h1SMcG0001187',
 'h1SMcG0001188',
 'h1SMcG0001189',
 'h1SMcG0001191',
 'h1SMcG0001193',
 'h1SMcG0001194',
 'h1SMcG0001195',
 'h1SMcG0001196',
 'h1SMcG0001197',
 'h1SMcG0001198',
 'h1SMcG0001200',
 'h1SMcG0001201',
 'h1SMcG0001203',
 'h1SMcG0001206',
 'h1SMcG0001207',
 'h1SMcG0001209',
 'h1SMcG0001210',
 'h1SMcG0001211',
 'h1SMcG0001212',
 'h1SMcG0001213',
 'h1SMcG0001214',
 'h1SMcG0001215',
 'h1SMcG0001216',
 'h1SMcG0001218',
 'h1SMcG0001220',
 'h1SMcG0001221',
 'h1SMcG0001222',
 'h1SMcG0001223',
 'h1SMcG0001224',
 'h1SMcG0001225',
 'h1SMcG0001226',
 'h1SMcG0001227',
 'h1SMcG0001228',
 'h1SMcG0001229',
 'h1SMcG0001230',
 'h1SMcG0001231',
 'h1SMcG0001232',
 'h1SMcG0001233',
 'h1SMcG0001234',
 'h1SMcG0001235',
 'h1SMcG0001236',
 'h1SMcG0001237',
 'h1SMcG0001238',
 'h1SMcG0001240',
 'h1SMcG0001241',
 'h1SMcG0001242',
 'h1SMcG0001243',
 'h1SMcG0001246',
 'h1SMcG0001247',
 'h1SMcG0001248',
 'h1SMcG0001249',
 'h1SMcG0001250',
 'h1SMcG0001251',
 'h1SMcG0001252',
 'h1SMcG0001253',
 'h1SMcG0001254',
 'h1SMcG0001255',
 'h1SMcG0001257',
 'h1SMcG0001258',
 'h1SMcG0001259',
 'h1SMcG0001260',
 'h1SMcG0001261',
 'h1SMcG0001263',
 'h1SMcG0001264',
 'h1SMcG0001265',
 'h1SMcG0001266',
 'h1SMcG0001267',
 'h1SMcG0001268',
 'h1SMcG0001270',
 'h1SMcG0001271',
 'h1SMcG0001272',
 'h1SMcG0001273',
 'h1SMcG0001274',
 'h1SMcG0001275',
 'h1SMcG0001277',
 'h1SMcG0001278',
 'h1SMcG0001279',
 'h1SMcG0001280',
 'h1SMcG0001281',
 'h1SMcG0001283',
 'h1SMcG0001284',
 'h1SMcG0001286',
 'h1SMcG0001287',
 'h1SMcG0001288',
 'h1SMcG0001289',
 ...]

In [29]:
identities_dge.to_csv("./outputs/06092023_smed_sero_identities.csv")

In [36]:
genes_dge.to_csv("./outputs/06092023_smed_sero_genes.csv")